LANG_TO_NAME = {
    "eng_Latn": "English",
    "ces_Latn": "Czech",
    "deu_Latn": "German",
    "ukr_Cyrl": "Ukrainian",
    "vie_Latn": "Vietnamese",
    "jpn_Jpan": "Japanese",
    "hye_Armn": "Armenian",
    "bel_Cyrl": "Belarusian",
    "kaz_Cyrl": "Kazakh",
    "rus_Cyrl": "Russian",
    "arz_Arab": "Egyptian Arabic",
    "zho_Hans": "Simplified Chinese",
    "zho_Hant": "Traditional Chinese",
    "zho_Hant_TW": "Traditional Chinese",
    "ekk_Latn": "Estonian",
    "isl_Latn": "Icelandic",
    "ind_Latn": "Indonesian",
    "kor_Hang": "Korean",
    "lij_Latn": "Ladin",
    "lld_Latn": "Ligurian",
    "sme_Latn": "Northern Sami",
    "tha_Thai": "Thai",
}
